replicaCount: 1

namespace: default

container:
  name: zuul
  
image:
  repository: deekshithsn/zuul
  pullPolicy: IfNotPresent
  
strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

service:
  type: NodePort
  port: 9999
  targetport: 9999
  name: zuul
  portname: http
  nodeport: 32470

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - ui
      topologyKey: "kubernetes.io/hostname"    