apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "shoe-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "shoe-helm.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "shoe-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name:  {{ .Release.Name }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort:  {{ .Values.service.targetport }}
          name:  {{ .Values.service.name }}