apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wishlist-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "wishlist-helm.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "wishlist-helm.selectorLabels" . | nindent 8  }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort:  {{ .Values.service.targetport }}
          name: {{ .Values.service.portname }}