replicaCount: 1

namespace: default

container:
  name: offer-ui
  
image:
  repository: deekshithsn/offer
  pullPolicy: IfNotPresent
  
strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

service:
  type: ClusterIP
  port: 1001
  targetport: 1001
  name: offer
  portname: http

