replicaCount: 1

namespace: default

container:
  name: wishlist-ui
  
image:
  repository: deekshithsn/wishlist
  pullPolicy: IfNotPresent
  
strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

service:
  type: ClusterIP
  port: 1003
  targetport: 5000
  name: wishlist
  portname: http