replicaCount: 1

namespace: default

container:
  name: shoe-ui
  
image:
  repository: deekshithsn/shoe
  pullPolicy: IfNotPresent
  
strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

service:
  type: ClusterIP
  port: 1002
  targetport: 1002
  name: shoe
  portname: http

