replicaCount: 1

namespace: default

container:
  name: ui
  
image:
  repository: deekshithsn/ui
  pullPolicy: IfNotPresent
  
strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

service:
  type: NodePort
  port: 8080
  targetport: 8080
  name: ui
  portname: http

