apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ui-helm.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ui-helm.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.portname }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}